# Generated by Django 4.2.1 on 2023-05-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_carbsdyhdrate_food_carbodyhdrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='carbodyhdrate',
            new_name='carbohyhdrate',
        ),
    ]
